version: '3.8'

services:
  frontend:
    build: .
    container_name: forca-client
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3

  test:
    image: node:18  # Usando a imagem Node.js para os testes
    container_name: forca-client-test
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && npm run test"]  # Rodar o npm install e depois os testes
    networks:
      - app-network
    depends_on:
      frontend:
        condition: service_healthy 
    restart: "no"  # Não reiniciar o contêiner após os testes

networks:
  app-network:
    driver: bridge
