version: '3.8'

services:
  frontend:
    build: .
    container_name: forca-client
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - forca-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3

  test:
    image: node:22  
    container_name: forca-client-test
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run test"]  
    networks:
      - forca-network
    depends_on:
      frontend:
        condition: service_healthy 
    restart: "always" 

networks:
  forca-network:
    external: true
