---
apiVersion: v1
kind: Namespace
metadata:
  name: app-k8s

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app-k8s
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: forca
  MYSQL_USER: root
  MYSQL_PASSWORD: root

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: app-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: app-k8s
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sg045/forcaapibackend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "root"
            - name: DB_NAME
              value: "forca"
            - name: JWT_SECRET
              value: chaveapiforca
            - name: OPENAI_API_KEY
              value: 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

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-k8s
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sg045/forcaapifront:latest   # troque pela imagem real
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-k8s
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
