name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Verifica o código do repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Etapa 2: Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Etapa 3: Configura Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Etapa 4: Construir as imagens e iniciar o ambiente com Docker Compose
      - name: Build and start Docker containers
        run: |
          docker-compose up --build -d  # Isso garante que o container esteja atualizado

      # Etapa 5: Rodar os testes dentro do container Docker
      - name: Run tests in Docker container
        run: |
          docker-compose exec frontend npm run test  # 'frontend' é o nome do serviço no docker-compose

      # Etapa 6: Opcionalmente, pode ser configurado um deploy (se necessário)
      # - name: Deploy to production
      #   run: |
      #     # Comandos para deploy, como subir para o AWS, Azure, ou outro
