name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Verifica o código do repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Etapa 2: Instala Docker e Docker Compose
      - name: Set up Docker and Docker Compose
        uses: docker/setup-buildx-action@v1

      # Etapa 3: Instala o Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Etapa 4: Puxa as últimas imagens e construa os containers
      - name: Pull and Build Docker containers
        run: |
          docker-compose pull  # Garante que as imagens mais recentes sejam baixadas
          docker-compose up --build --abort-on-container-exit  # Não usa o -d para ver os logs ao vivo

      # Etapa 5: Rodar os testes dentro do container Docker
      - name: Run tests in Docker container
        run: |
          docker-compose run --rm test  # Rodar o serviço de testes configurado no docker-compose

      # Etapa 6: (Opcional) Deploy, caso necessário
      # - name: Deploy to production
      #   run: |
      #     # Comandos para deploy, como subir para o AWS, Azure, ou outro
